export type { AstPath } from "./ast_path.js";
export { astPathsEqual } from "./ast_path.js";
export {
  BaseDocumentProjection,
  type BaseDocumentProjectionInput,
  type BaseParagraphProjection,
  type BaseProjectionSchema,
  type BaseTextRunProjection,
  type ProjectionSnapshot,
} from "./projection.js";
export {
  BaseProjectionUpdate,
  type BaseProjectionImpact,
  type BaseProjectionUpdateInput,
  type FullProjectionReason,
  type RootChildRange,
} from "./projection_update.js";
export {
  BreditorDomRenderer,
  type ProjectionFallbackReason,
  type ProjectionRenderMode,
  type ProjectionRenderOutcome,
  type RenderedProjection,
} from "./dom_renderer.js";
export {
  BreditorDomSelectionBridge,
  type DomFocusObservation,
  type DomSelectionAffinityPolicy,
  type DomSelectionObservation,
  type DomSelectionOrigin,
  type DomSelectionUnavailableReason,
  type DomSelectionWriteOutcome,
} from "./dom_selection.js";
export {
  BaseRangeSelection,
  type BaseChildrenSelectionPoint,
  type BaseEditorSelection,
  type BaseRangeOrder,
  type BaseRangeSelectionInput,
  type BaseSelectionPoint,
  type BaseTextSelectionPoint,
  type SelectionAffinity,
} from "./selection.js";
export type {
  BrowserSelectionError,
  BrowserSelectionErrorCode,
  BrowserSelectionResult,
} from "./selection_result.js";
export type {
  BrowserProjectionError,
  BrowserProjectionErrorCode,
  BrowserProjectionResult,
} from "./result.js";
export {
  consumeSemanticProjection,
  consumeSemanticProjectionUpdate,
  type SemanticProjectionImpact,
  type SemanticProjectionUpdateView,
  type SemanticProjectionView,
} from "./wasm_projection_adapter.js";
export {
  consumeSemanticSelection,
  semanticRangeSelectionScalars,
  type SemanticRangeSelectionScalars,
  type SemanticSelectionPointKind,
  type SemanticSelectionView,
} from "./wasm_selection_adapter.js";
export {
  BASE_ACTION_IDS,
  MAX_BROWSER_COMMAND_TEXT_UTF16,
  MAX_BROWSER_COMMAND_TEXT_UTF8,
  browserCommandTextIsAdmissible,
  closeHistoryGroupRequest,
  historyRequest,
  isEditorCommandRequest,
  isEngineCommand,
  noInputActionRequest,
  noSelectionSync,
  preserveSelectionSync,
  rangeSelectionSync,
  selectionSynchronizationRequest,
  stringActionRequest,
  type EditorCommand,
  type EditorCommandRequest,
  type EditorCommandRequirements,
  type EditorCommandSource,
  type EditorDeliveryAuthority,
  type EditorDeliveryToken,
  type EditorSelectionSync,
  type EngineCommand,
  type EngineCommandRequest,
} from "./editor_command.js";
export {
  BreditorCommandQueue,
  DEFAULT_COMMAND_QUEUE_CAPACITY,
  MAX_COMMAND_QUEUE_CAPACITY,
  type CommandQueueDelivery,
  type CommandQueueFailure,
  type CommandQueueFailureCode,
  type CommandQueueObserver,
  type CommandQueueSubmission,
  type EditorCommandExecutor,
} from "./command_queue.js";
export {
  translateBeforeInput,
  type BeforeInputSnapshot,
  type BeforeInputTranslation,
} from "./beforeinput.js";
export {
  translateKeyDown,
  type KeyboardSnapshot,
  type KeyboardTranslation,
  type KeyboardTranslationPolicy,
} from "./keyboard.js";
export {
  cutDeleteRequest,
  pasteInsertRequest,
} from "./clipboard_command.js";
export {
  MAX_CLIPBOARD_FRAGMENT_HTML_UTF16,
  MAX_CLIPBOARD_FRAGMENT_HTML_UTF8,
  MAX_CLIPBOARD_FRAGMENT_TEXT_UTF16,
  MAX_CLIPBOARD_FRAGMENT_TEXT_UTF8,
  serializeClipboardSelection,
  type ClipboardFragmentError,
  type ClipboardFragmentErrorCode,
  type ClipboardFragmentSerialization,
  type ClipboardFragmentSerializationResult,
} from "./clipboard_fragment.js";
export {
  MAX_CLIPBOARD_HTML_DEPTH,
  MAX_CLIPBOARD_HTML_NODES,
  MAX_CLIPBOARD_HTML_PARAGRAPHS,
  MAX_CLIPBOARD_HTML_SOURCE_UTF16,
  MAX_CLIPBOARD_HTML_SOURCE_UTF8,
  parseClipboardHtmlToPlainText,
  type ClipboardHtmlError,
  type ClipboardHtmlErrorCode,
  type ClipboardHtmlParseResult,
} from "./clipboard_html.js";
export {
  BreditorClipboardController,
  type ClipboardControllerClipboardState,
  type ClipboardControllerCommandState,
  type ClipboardControllerDisposition,
  type ClipboardControllerFailureReason,
  type ClipboardControllerIgnoreReason,
  type ClipboardControllerOperation,
  type ClipboardControllerPartialState,
} from "./clipboard_controller.js";
export {
  BaseTargetRange,
  baseTargetRangesEqual,
  type BaseTargetRangeInput,
} from "./target_range.js";
export { mapDomTargetRange } from "./dom_target_range.js";
export type {
  BrowserEventBlockReason,
  BrowserEventDisposition,
  BrowserEventIgnoreReason,
  BrowserEventReconcileReason,
  BrowserSelectionChangeBlockReason,
  BrowserSelectionChangeDisposition,
  BrowserSelectionChangeIgnoreReason,
} from "./event_disposition.js";
export {
  BreditorBrowserEventController,
  type BrowserEventControllerOptions,
} from "./browser_event_controller.js";
export {
  BreditorCompositionController,
  type CompositionCommandSubmission,
  type CompositionControllerDisposition,
  type CompositionControllerIgnoreReason,
  type CompositionControllerNotification,
  type CompositionControllerOptions,
  type CompositionControllerRecovery,
  type CompositionControllerResume,
  type CompositionControllerTerminal,
} from "./composition_controller.js";
export type {
  CompositionAbortReason,
  CompositionError,
  CompositionErrorCode,
  CompositionSettlement,
} from "./composition_result.js";
export type { CompositionPhase } from "./composition_state.js";
export {
  MAX_BROWSER_ACTION_STATE_ENTRIES,
  MAX_BROWSER_ACTION_STATE_BATCH_TEXT_BYTES,
  MAX_BROWSER_ACTION_STATE_BATCH_VALUE_COUNT,
  MAX_BROWSER_ACTION_STATE_VALUE_JSON_BATCH_BYTES,
  MAX_BROWSER_ACTION_STATE_VALUE_JSON_BYTES,
  consumeWasmActionStates,
  type BrowserActionStateActivation,
  type BrowserActionStateAvailability,
  type BrowserActionStateEntry,
  type BrowserActionStateReadError,
  type BrowserActionStateReadResult,
  type BrowserActionStateSnapshot,
  type BrowserActionStateValue,
  type BrowserActionStateValueContract,
  type BrowserActionStateValueStatus,
  type BrowserActionValue,
  type BrowserActionValueArray,
  type BrowserActionValueObject,
  type WasmActionStateEntryStatus,
  type WasmActionStateErrorView,
  type WasmActionStateExpectedSnapshot,
  type WasmActionStateReadPort,
  type WasmActionStateSnapshotView,
  type WasmActionStateStringResultView,
  type WasmActionStatesResultView,
} from "./wasm_action_state_adapter.js";
export {
  BreditorActionStateStore,
  MAX_ACTION_STATE_STORE_LISTENERS,
  type ActionStateStoreError,
  type ActionStateStoreListener,
  type ActionStateStoreRefreshResult,
  type ActionStateStoreStatus,
} from "./action_state_store.js";
export {
  BASE_TOOLBAR_STATE_IDS,
  DEFAULT_TOOLBAR_MANIFEST,
  MAX_TOOLBAR_CONTROLS,
  MAX_TOOLBAR_GROUP_UTF16,
  MAX_TOOLBAR_LABEL_UTF16,
  MAX_TOOLBAR_LABEL_UTF8,
  createToolbarManifest,
  type ToolbarCommandDeclaration,
  type ToolbarControlDeclaration,
  type ToolbarManifest,
} from "./toolbar_manifest.js";
export {
  BreditorToolbar,
  MAX_TOOLBAR_LIFECYCLE_SUBSCRIBERS,
  MAX_TOOLBAR_STATE_ENTRIES,
  toolbarCommandDispatchResult,
  toolbarCommandRequest,
  type BreditorToolbarState,
  type BreditorToolbarSubscriber,
  type ToolbarActionStateEntry,
  type ToolbarActionStateSnapshot,
  type ToolbarActionStateStore,
  type ToolbarCommandDispatcher,
  type ToolbarCommandDispatchResult,
  type ToolbarCommandInvocation,
} from "./toolbar.js";
export {
  MAX_BROWSER_SESSION_CHECKPOINT_JSON_BYTES,
  consumeWasmSessionCheckpoint,
  type BrowserSessionCheckpoint,
  type BrowserSessionCheckpointReadError,
  type BrowserSessionCheckpointReadResult,
  type WasmSessionCheckpointErrorView,
  type WasmSessionCheckpointExpectedSnapshot,
  type WasmSessionCheckpointReadPort,
  type WasmSessionCheckpointStringResultView,
} from "./wasm_session_checkpoint.js";
export {
  restoreWasmEngine,
  type BrowserWasmEngineRestoreError,
  type BrowserWasmEngineRestoreResult,
  type WasmEngineRestoreFactoryView,
  type WasmEngineRestoreResultView,
  type WasmRestoredEngineView,
} from "./wasm_engine_restore.js";
export {
  IndexedDbSessionCheckpointStore,
  MAX_SESSION_CHECKPOINT_UTF8_BYTES,
  SESSION_CHECKPOINT_DATABASE_NAME,
  SESSION_CHECKPOINT_DATABASE_VERSION,
  SESSION_CHECKPOINT_OBJECT_STORE_NAME,
  SESSION_CHECKPOINT_SLOT,
  type IndexedDbSessionCheckpointCasToken,
  type IndexedDbSessionCheckpointError,
  type IndexedDbSessionCheckpointErrorCode,
  type IndexedDbSessionCheckpointLoadResult,
  type IndexedDbSessionCheckpointSaveResult,
  type IndexedDbSessionCheckpointStoreOptions,
} from "./indexeddb_session_checkpoint.js";
export {
  BreditorSessionCheckpointAutosave,
  DEFAULT_SESSION_CHECKPOINT_AUTOSAVE_DELAY_MS,
  DEFAULT_SESSION_CHECKPOINT_AUTOSAVE_MAX_LATENCY_MS,
  MAX_SESSION_CHECKPOINT_AUTOSAVE_DELAY_MS,
  MAX_SESSION_CHECKPOINT_AUTOSAVE_FLUSH_WAITERS,
  MAX_SESSION_CHECKPOINT_AUTOSAVE_STATUS_OBSERVERS,
  MAX_SESSION_CHECKPOINT_AUTOSAVE_UTF8_BYTES,
  type SessionCheckpointAutosaveCapturePort,
  type SessionCheckpointAutosaveCaptureResult,
  type SessionCheckpointAutosaveFailure,
  type SessionCheckpointAutosaveFailureCode,
  type SessionCheckpointAutosaveFlushResult,
  type SessionCheckpointAutosaveOptions,
  type SessionCheckpointAutosaveSavePort,
  type SessionCheckpointAutosaveSaveResult,
  type SessionCheckpointAutosaveScheduler,
  type SessionCheckpointAutosaveStatus,
  type SessionCheckpointAutosaveStatusObserver,
} from "./session_checkpoint_autosave.js";
export {
  BreditorWasmCommandAdapter,
  MAX_WASM_CORE_COMMIT_OBSERVERS,
  isEngineCommandRequest,
  type BreditorWasmCommandAdapterOptions,
  type WasmCommandEngineView,
  type WasmCommandError,
  type WasmCommandErrorView,
  type WasmCommandObservationView,
  type WasmCommandOutcome,
  type WasmCommandRenderMetadata,
  type WasmCommandResultView,
  type WasmCommandSelectionOutcome,
  type WasmCommandSequenceOutcome,
  type WasmCommandSnapshot,
  type WasmCompositionLeaseRestoreOutcome,
  type WasmCoreCommit,
  type WasmCoreCommitObserver,
  type WasmRenderReconciliationOutcome,
  type WasmSelectionResultView,
} from "./wasm_command_adapter.js";
export {
  BREDITOR_WASM_ABI_VERSION,
  MAX_WASM_BOOTSTRAP_HISTORY_CAPACITY,
  bootstrapWasmEngine,
  isOwnedBrowserWasmEngineBootstrapResult,
  type BrowserWasmEngineBootstrapError,
  type BrowserWasmEngineBootstrapResult,
  type WasmBootstrappedEngineView,
  type WasmDocumentBootstrapSource,
  type WasmEngineBootstrapFactoryView,
  type WasmEngineBootstrapModuleView,
  type WasmEngineBootstrapResultView,
  type WasmEngineBootstrapSource,
  type WasmProjectionReadResultView,
  type WasmSessionCheckpointBootstrapSource,
} from "./wasm_engine_bootstrap.js";
export {
  BreditorBrowserEventRouter,
  MAX_BROWSER_EVENT_ROUTER_SUBSCRIBERS,
  type BrowserEventRouterFaultReason,
  type BrowserEventRouterOptions,
  type BrowserEventRouterStatus,
  type BrowserEventRouterSubscriber,
} from "./browser_event_router.js";
export {
  BreditorBrowserEditor,
  MAX_BROWSER_EDITOR_LABEL_UTF16,
  MAX_BROWSER_EDITOR_SUBSCRIBERS,
  openBreditorBrowserEditor,
  type BreditorBrowserEditorFaultReason,
  type BreditorBrowserEditorOpenError,
  type BreditorBrowserEditorOpenResult,
  type BreditorBrowserEditorOptions,
  type BreditorBrowserEditorPersistenceOptions,
  type BreditorBrowserEditorPersistenceResult,
  type BreditorBrowserEditorPersistenceStatus,
  type BreditorBrowserEditorSnapshot,
  type BreditorBrowserEditorStatus,
  type BreditorBrowserEditorSubscriber,
  type BreditorBrowserDocumentSnapshot,
  type BreditorBrowserInitialDocument,
  type BreditorBrowserToolbarOptions,
  type BreditorBrowserWasmFactory,
  type BreditorBrowserWasmModule,
} from "./browser_editor.js";
