//! Strict versioned codecs for untrusted persisted data.

mod commit_error;
mod commit_json;
mod diagnostic;
mod document_encoding;
mod document_json;
mod document_preflight;
mod editor_state_encoding;
mod editor_state_error;
mod editor_state_json;
mod editor_value_payload_v1;
mod error;
mod json_size;
mod local_log_checkpoint_error;
mod local_log_checkpoint_json;
mod local_log_checkpoint_limits;
mod local_log_checkpoint_tombstones_v1;
mod local_log_entry_error;
mod local_log_entry_json;
mod local_log_frame_binding;
mod local_log_frame_checksum;
mod local_log_frame_codec;
mod local_log_frame_error;
mod local_log_frame_limits;
mod local_log_frame_scan;
mod local_log_storage_attempt_aborted;
mod local_log_storage_attempt_aborted_resubmit;
mod local_log_storage_attempt_plan;
mod local_log_storage_attempt_preparation_error;
mod local_log_storage_attempt_request;
mod local_log_storage_attempt_terminal_attestation;
mod local_log_storage_attempt_terminal_failure;
mod local_log_storage_attempt_terminal_outcome;
mod local_log_storage_attempt_transition_error;
mod local_log_storage_generation_binding;
mod local_log_storage_generation_checkpoint_preflight;
mod local_log_storage_generation_decode;
mod local_log_storage_generation_decode_from_selected;
mod local_log_storage_generation_encode;
mod local_log_storage_generation_encode_from_selected;
mod local_log_storage_generation_error;
mod local_log_storage_generation_frame_v1;
mod local_log_storage_generation_json;
mod local_log_storage_generation_limits;
mod local_log_storage_generation_manifest;
mod local_log_storage_generation_preparation_inputs;
mod local_log_storage_generation_prepare;
mod local_log_storage_generation_prepare_from_selected;
#[cfg(test)]
mod local_log_storage_generation_selected_tests;
#[cfg(test)]
mod local_log_storage_generation_tests;
mod local_log_storage_host_attested_committed;
mod local_log_storage_issued_attempt;
mod local_log_storage_mutation_fence_binding;
mod local_log_storage_mutation_fence_binding_compare_later;
mod local_log_storage_mutation_fence_binding_from_selected;
mod local_log_storage_mutation_fence_binding_observation_error;
mod local_log_storage_not_attempted;
mod local_log_storage_not_attempted_resubmit;
mod local_log_storage_prepared_attempt;
mod local_log_storage_prepared_begin_attempt;
mod local_log_storage_retained_attempt;
mod local_log_storage_retired_generation_observation;
mod local_log_storage_retired_generation_observation_error;
mod local_log_storage_retired_transaction_binding;
mod local_log_storage_root_attempt_prepare;
mod local_log_storage_root_binding;
mod local_log_storage_root_decode;
mod local_log_storage_root_encode;
mod local_log_storage_root_error;
mod local_log_storage_root_json;
mod local_log_storage_root_preparation_inputs;
mod local_log_storage_root_prepare;
mod local_log_storage_root_resolution;
mod local_log_storage_root_resolution_adapter_request;
#[cfg(test)]
mod local_log_storage_root_resolution_adversarial_tests;
mod local_log_storage_root_resolution_apply;
mod local_log_storage_root_resolution_begin;
mod local_log_storage_root_resolution_collision_reason;
mod local_log_storage_root_resolution_evidence;
mod local_log_storage_root_resolution_failure;
mod local_log_storage_root_resolution_observation;
mod local_log_storage_root_resolution_outcome;
mod local_log_storage_root_resolution_request;
mod local_log_storage_root_resolution_restart;
mod local_log_storage_root_resolution_retry;
mod local_log_storage_root_resolution_source;
mod local_log_storage_root_resolution_source_kind;
mod local_log_storage_root_resolution_start_error;
mod local_log_storage_root_resolution_start_failure;
mod local_log_storage_root_resolution_transition_error;
mod local_log_storage_root_resolved;
mod local_log_storage_root_retry_eligible_at_resolution;
mod local_log_storage_root_selection;
#[cfg(test)]
mod local_log_storage_root_tests;
mod local_log_storage_rotation_attempt_prepare;
mod local_log_storage_rotation_resolution;
mod local_log_storage_rotation_resolution_adapter_request;
#[cfg(test)]
mod local_log_storage_rotation_resolution_adversarial_tests;
mod local_log_storage_rotation_resolution_apply;
mod local_log_storage_rotation_resolution_begin;
mod local_log_storage_rotation_resolution_collision_reason;
mod local_log_storage_rotation_resolution_evidence;
mod local_log_storage_rotation_resolution_failure;
mod local_log_storage_rotation_resolution_observation;
mod local_log_storage_rotation_resolution_outcome;
mod local_log_storage_rotation_resolution_request;
mod local_log_storage_rotation_resolution_restart;
mod local_log_storage_rotation_resolution_retry;
mod local_log_storage_rotation_resolution_source;
mod local_log_storage_rotation_resolution_source_kind;
mod local_log_storage_rotation_resolution_start_error;
mod local_log_storage_rotation_resolution_start_failure;
mod local_log_storage_rotation_resolution_transition_error;
mod local_log_storage_rotation_resolved;
mod local_log_storage_rotation_retry_eligible_at_resolution;
mod local_log_storage_selected_active_generation_validate_retired;
mod local_log_storage_selected_binding;
mod local_log_storage_selected_binding_change;
mod local_log_storage_selected_binding_compare_later;
mod local_log_storage_selected_binding_observation_error;
mod local_log_storage_selected_envelope_error;
mod local_log_storage_selected_envelope_validate;
mod local_log_storage_selected_generation_binding;
mod local_log_storage_selected_json;
mod local_log_storage_selected_root;
mod local_log_storage_selected_root_error;
mod local_log_storage_selected_root_normalize;
mod local_log_storage_selected_rotation_normalize;
#[cfg(test)]
mod local_log_storage_selected_tests;
mod local_log_storage_selection_kind;
mod local_log_storage_selection_receipt_binding;
mod local_log_storage_uncertain_adapter_request;
mod local_log_storage_uncertain_attempt;
mod local_log_storage_uncertain_attempt_match;
mod local_log_storage_uncertain_observe_terminal;
mod local_log_storage_uncertain_resubmit;
mod local_log_storage_writer_fence_acquisition_plan;
mod local_log_storage_writer_fence_acquisition_preparation_error;
mod local_log_storage_writer_fence_acquisition_preparation_failure;
mod local_log_storage_writer_fence_acquisition_prepare;
#[cfg(test)]
mod local_log_storage_writer_fence_adversarial_tests;
mod local_log_tail_begin;
mod local_log_tail_compaction;
mod local_log_tail_compaction_outcome;
mod local_log_tail_compaction_reauthorization;
mod local_log_tail_cursor;
mod local_log_tail_error;
mod local_log_tail_failure;
mod local_log_tail_observation;
mod local_log_tail_step;
mod operation_error;
mod operation_json;
mod operation_payload_v1;
mod operation_preflight;
mod operation_sequence_v1;
mod session_checkpoint_entries_v1;
mod session_checkpoint_error;
mod session_checkpoint_json;
mod session_checkpoint_limits;
mod transaction_error;
mod transaction_json;
mod transaction_payload_v1;

pub use commit_error::{
    CommitApplicationError, CommitApplicationErrorCode, CommitCodecError, CommitRecordError,
    CommitRecordErrorCode, CommitRecordLocation,
};
pub use commit_json::{COMMIT_FORMAT, COMMIT_FORMAT_VERSION, CommitJsonCodec};
pub use diagnostic::{BoundedDiagnostic, MAX_DIAGNOSTIC_PREVIEW_BYTES};
pub use document_json::{DOCUMENT_FORMAT, DOCUMENT_FORMAT_VERSION, DocumentJsonCodec};
pub use editor_state_error::{
    EditorStateCodecError, EditorStateRecordError, EditorStateRecordErrorCode,
    EditorStateRecordLocation,
};
pub use editor_state_json::{
    EDITOR_STATE_FORMAT, EDITOR_STATE_FORMAT_VERSION, EditorStateJsonCodec,
};
pub use error::{CodecErrorCode, DocumentCodecError, JsonFailure, JsonFailureKind};
pub use local_log_checkpoint_error::{
    LocalLogCheckpointBindingField, LocalLogCheckpointCodecError, LocalLogCheckpointRecordError,
    LocalLogCheckpointRecordErrorCode, LocalLogCheckpointRecordLocation,
    LocalLogCheckpointResourceLimit, LocalLogCheckpointResourceLimitCode,
    LocalLogCheckpointTopologyError, LocalLogCheckpointTopologyErrorCode,
};
pub use local_log_checkpoint_json::{
    LOCAL_LOG_CHECKPOINT_FORMAT, LOCAL_LOG_CHECKPOINT_FORMAT_VERSION, LocalLogCheckpointJsonCodec,
};
pub use local_log_checkpoint_limits::{
    DEFAULT_LOCAL_LOG_CHECKPOINT_MAX_REPLAY_TOMBSTONES, LocalLogCheckpointLimits,
};
pub use local_log_entry_error::{
    LocalLogCommitEventKind, LocalLogEntryCodecError, LocalLogEntryRecordError,
    LocalLogEntryRecordErrorCode, LocalLogEntryRecordLocation,
};
pub use local_log_entry_json::{
    LOCAL_LOG_ENTRY_FORMAT, LOCAL_LOG_ENTRY_FORMAT_VERSION, LocalLogEntryJsonCodec,
};
pub use local_log_frame_binding::LocalLogFrameBinding;
pub use local_log_frame_codec::{
    LOCAL_LOG_FRAME_FORMAT_VERSION, LOCAL_LOG_FRAME_HEADER_BYTES, LOCAL_LOG_FRAME_MAGIC,
    LocalLogFrameCodec,
};
pub use local_log_frame_error::{LocalLogFrameCodecError, LocalLogFrameErrorCode};
pub use local_log_frame_limits::{DEFAULT_LOCAL_LOG_FRAME_MAX_PAYLOAD_BYTES, LocalLogFrameLimits};
pub use local_log_frame_scan::{
    BorrowedLocalLogFrame, LocalLogFrameScan, LocalLogFrameTruncation, LocalLogFrameTruncationStage,
};
pub use local_log_storage_attempt_aborted::LocalLogStorageAttemptAborted;
pub use local_log_storage_attempt_preparation_error::{
    LocalLogStorageAttemptPreparationError, LocalLogStorageAttemptPreparationErrorCode,
};
pub use local_log_storage_attempt_request::{
    LocalLogStorageAttemptRequest, LocalLogStorageRootAttemptRequest,
    LocalLogStorageRotationAttemptRequest,
};
pub use local_log_storage_attempt_terminal_attestation::{
    LocalLogStorageAttemptTerminalAttestation, LocalLogStorageAttemptTerminalAttestationKind,
};
pub use local_log_storage_attempt_terminal_failure::LocalLogStorageAttemptTerminalFailure;
pub use local_log_storage_attempt_terminal_outcome::LocalLogStorageAttemptTerminalOutcome;
pub use local_log_storage_attempt_transition_error::{
    LocalLogStorageAttemptTransitionError, LocalLogStorageAttemptTransitionErrorCode,
};
pub use local_log_storage_generation_binding::{
    LocalLogStorageGenerationBinding, LocalLogStorageGenerationBindingError,
};
pub use local_log_storage_generation_error::{
    LocalLogStorageGenerationBindingField, LocalLogStorageGenerationCodecError,
    LocalLogStorageGenerationContinuityError, LocalLogStorageGenerationContinuityErrorCode,
    LocalLogStorageGenerationJsonFailure, LocalLogStorageGenerationRecordError,
    LocalLogStorageGenerationRecordErrorCode, LocalLogStorageGenerationRecordLocation,
    LocalLogStorageGenerationResourceLimit, LocalLogStorageGenerationResourceLimitCode,
    LocalLogStorageGenerationTopologyError, LocalLogStorageGenerationTopologyErrorCode,
};
pub use local_log_storage_generation_frame_v1::LocalLogStorageGenerationFrameV1;
pub use local_log_storage_generation_json::{
    LOCAL_LOG_STORAGE_GENERATION_FORMAT, LOCAL_LOG_STORAGE_GENERATION_FORMAT_VERSION,
    LocalLogStorageGenerationJsonCodec,
};
pub use local_log_storage_generation_limits::{
    DEFAULT_LOCAL_LOG_STORAGE_GENERATION_MAX_CHECKPOINT_JSON_BYTES,
    DEFAULT_LOCAL_LOG_STORAGE_GENERATION_MAX_INPUT_BYTES,
    DEFAULT_LOCAL_LOG_STORAGE_GENERATION_MAX_OUTPUT_BYTES, LocalLogStorageGenerationLimits,
};
pub use local_log_storage_generation_manifest::LocalLogStorageGenerationManifest;
pub(crate) use local_log_storage_generation_manifest::LocalLogStorageGenerationManifestParts;
pub use local_log_storage_generation_preparation_inputs::LocalLogStorageGenerationPreparationInputs;
pub use local_log_storage_host_attested_committed::LocalLogStorageHostAttestedCommitted;
pub use local_log_storage_mutation_fence_binding::LocalLogStorageMutationFenceBinding;
pub use local_log_storage_mutation_fence_binding_observation_error::{
    LocalLogStorageMutationFenceBindingObservationError,
    LocalLogStorageMutationFenceBindingObservationErrorCode,
};
pub use local_log_storage_not_attempted::LocalLogStorageNotAttempted;
pub use local_log_storage_prepared_attempt::LocalLogStoragePreparedAttempt;
pub use local_log_storage_retired_generation_observation::LocalLogStorageRetiredGenerationObservation;
pub use local_log_storage_retired_generation_observation_error::{
    LocalLogStorageRetiredGenerationMismatchField,
    LocalLogStorageRetiredGenerationObservationError,
    LocalLogStorageRetiredGenerationObservationErrorCode,
};
pub use local_log_storage_retired_transaction_binding::{
    LocalLogStorageRetiredTransactionBinding, LocalLogStorageRetiredTransactionBindingError,
    LocalLogStorageRetiredTransactionBindingErrorCode,
};
pub use local_log_storage_root_binding::LocalLogStorageRootBinding;
pub use local_log_storage_root_error::{
    LocalLogStorageRootBindingField, LocalLogStorageRootCodecError, LocalLogStorageRootJsonFailure,
    LocalLogStorageRootRecordError, LocalLogStorageRootRecordErrorCode,
    LocalLogStorageRootRecordLocation, LocalLogStorageRootResourceLimit,
    LocalLogStorageRootResourceLimitCode, LocalLogStorageRootTopologyError,
    LocalLogStorageRootTopologyErrorCode,
};
pub use local_log_storage_root_json::{
    LOCAL_LOG_STORAGE_ROOT_FORMAT, LOCAL_LOG_STORAGE_ROOT_FORMAT_VERSION,
    LocalLogStorageRootJsonCodec,
};
pub use local_log_storage_root_preparation_inputs::LocalLogStorageRootPreparationInputs;
pub use local_log_storage_root_resolution::LocalLogStorageRootResolution;
pub use local_log_storage_root_resolution_collision_reason::LocalLogStorageRootResolutionCollisionReason;
pub use local_log_storage_root_resolution_evidence::LocalLogStorageRootResolutionEvidence;
pub use local_log_storage_root_resolution_failure::LocalLogStorageRootResolutionFailure;
pub use local_log_storage_root_resolution_observation::{
    LocalLogStorageRootDirectSuccessorObservation, LocalLogStorageRootOtherScopeObservation,
    LocalLogStorageRootResolutionBrokenAssociation, LocalLogStorageRootResolutionIdentityCollision,
    LocalLogStorageRootResolutionObservation, LocalLogStorageRootResolutionObservationKind,
    LocalLogStorageRootRetiredObservation, LocalLogStorageRootSelectedObservation,
    LocalLogStorageRootSupersededObservation,
};
pub use local_log_storage_root_resolution_outcome::{
    LocalLogStorageRootResolutionOutcome, LocalLogStorageRootResolutionOutcomeKind,
};
pub use local_log_storage_root_resolution_request::LocalLogStorageRootResolutionRequest;
pub use local_log_storage_root_resolution_source_kind::LocalLogStorageRootResolutionSourceKind;
pub use local_log_storage_root_resolution_start_error::{
    LocalLogStorageRootResolutionStartError, LocalLogStorageRootResolutionStartErrorCode,
};
pub use local_log_storage_root_resolution_start_failure::LocalLogStorageRootResolutionStartFailure;
pub use local_log_storage_root_resolution_transition_error::{
    LocalLogStorageRootResolutionTransitionError, LocalLogStorageRootResolutionTransitionErrorCode,
};
pub use local_log_storage_root_resolved::LocalLogStorageRootResolved;
pub use local_log_storage_root_retry_eligible_at_resolution::LocalLogStorageRootRetryEligibleAtResolution;
pub use local_log_storage_root_selection::LocalLogStorageRootSelection;
pub(crate) use local_log_storage_root_selection::LocalLogStorageRootSelectionParts;
pub use local_log_storage_rotation_resolution::LocalLogStorageRotationResolution;
pub use local_log_storage_rotation_resolution_collision_reason::LocalLogStorageRotationResolutionCollisionReason;
pub use local_log_storage_rotation_resolution_evidence::LocalLogStorageRotationResolutionEvidence;
pub use local_log_storage_rotation_resolution_failure::LocalLogStorageRotationResolutionFailure;
pub use local_log_storage_rotation_resolution_observation::{
    LocalLogStorageRotationDifferentCurrentObservation,
    LocalLogStorageRotationDirectSuccessorObservation,
    LocalLogStorageRotationIndexedRetiredTransactionObservation,
    LocalLogStorageRotationOtherScopeObservation,
    LocalLogStorageRotationPriorStillSelectedObservation,
    LocalLogStorageRotationResolutionBrokenAssociation,
    LocalLogStorageRotationResolutionIdentityCollision,
    LocalLogStorageRotationResolutionObservation, LocalLogStorageRotationResolutionObservationKind,
    LocalLogStorageRotationRetiredObservation, LocalLogStorageRotationSelectedObservation,
    LocalLogStorageRotationSupersededObservation,
};
pub use local_log_storage_rotation_resolution_outcome::{
    LocalLogStorageRotationResolutionOutcome, LocalLogStorageRotationResolutionOutcomeKind,
};
pub use local_log_storage_rotation_resolution_request::LocalLogStorageRotationResolutionRequest;
pub use local_log_storage_rotation_resolution_source_kind::LocalLogStorageRotationResolutionSourceKind;
pub use local_log_storage_rotation_resolution_start_error::{
    LocalLogStorageRotationResolutionStartError, LocalLogStorageRotationResolutionStartErrorCode,
};
pub use local_log_storage_rotation_resolution_start_failure::LocalLogStorageRotationResolutionStartFailure;
pub use local_log_storage_rotation_resolution_transition_error::{
    LocalLogStorageRotationResolutionTransitionError,
    LocalLogStorageRotationResolutionTransitionErrorCode,
};
pub use local_log_storage_rotation_resolved::LocalLogStorageRotationResolved;
pub use local_log_storage_rotation_retry_eligible_at_resolution::LocalLogStorageRotationRetryEligibleAtResolution;
pub use local_log_storage_selected_binding::{
    LocalLogStorageSelectedBinding, LocalLogStorageSelectedBindingError,
    LocalLogStorageSelectedBindingErrorCode, LocalLogStorageSelectedGenerationMismatchField,
    LocalLogStorageSelectedReceiptMismatchField,
};
pub use local_log_storage_selected_binding_change::LocalLogStorageSelectedBindingChange;
pub use local_log_storage_selected_binding_observation_error::{
    LocalLogStorageSelectedBindingObservationError,
    LocalLogStorageSelectedBindingObservationErrorCode,
};
pub use local_log_storage_selected_envelope_error::{
    LocalLogStorageSelectedEnvelopeError, LocalLogStorageSelectedEnvelopeErrorCode,
};
pub use local_log_storage_selected_generation_binding::{
    LocalLogStorageSelectedActiveGenerationBinding,
    LocalLogStorageSelectedCheckpointGenerationBinding,
    LocalLogStorageSelectedCheckpointGenerationState,
};
pub use local_log_storage_selected_json::LocalLogStorageSelectedJsonCodec;
pub use local_log_storage_selected_root::LocalLogStorageSelectedRoot;
pub use local_log_storage_selected_root_error::{
    LocalLogStorageSelectedRootError, LocalLogStorageSelectedRootErrorCode,
    LocalLogStorageSelectedRootGenerationField, LocalLogStorageSelectedRootReceiptField,
    LocalLogStorageSelectedRootValueRole,
};
pub use local_log_storage_selection_kind::LocalLogStorageSelectionKind;
pub use local_log_storage_selection_receipt_binding::{
    LocalLogStorageSelectionReceiptBinding, LocalLogStorageSelectionReceiptBindingError,
    LocalLogStorageSelectionReceiptBindingErrorCode,
};
pub use local_log_storage_uncertain_attempt::LocalLogStorageUncertainAttempt;
pub use local_log_storage_writer_fence_acquisition_plan::LocalLogStorageWriterFenceAcquisitionPlan;
pub use local_log_storage_writer_fence_acquisition_preparation_error::{
    LocalLogStorageWriterFenceAcquisitionPreparationError,
    LocalLogStorageWriterFenceAcquisitionPreparationErrorCode,
};
pub use local_log_storage_writer_fence_acquisition_preparation_failure::LocalLogStorageWriterFenceAcquisitionPreparationFailure;
pub use local_log_tail_compaction_outcome::LocalLogTailCompactionOutcome;
pub use local_log_tail_cursor::LocalLogTailCursor;
pub use local_log_tail_error::{LocalLogTailError, LocalLogTailErrorCode};
pub use local_log_tail_failure::LocalLogTailFailure;
pub use local_log_tail_step::{LocalLogTailStatus, LocalLogTailStep};
pub use operation_error::{
    OperationCodecError, OperationFragmentField, OperationOffsetField, OperationPathField,
    OperationRecordError, OperationRecordErrorCode, OperationRecordLocation,
};
pub use operation_json::{OPERATION_FORMAT, OPERATION_FORMAT_VERSION, OperationJsonCodec};
pub use session_checkpoint_error::{
    RetainedResourceKind, SessionCheckpointApplicationError, SessionCheckpointApplicationErrorCode,
    SessionCheckpointCodecError, SessionCheckpointRecordError, SessionCheckpointRecordErrorCode,
    SessionCheckpointRecordLocation, SessionCheckpointReplayDirection,
    SessionCheckpointResourceLimit, SessionCheckpointResourceLimitCode,
    SessionCheckpointTopologyError, SessionCheckpointTopologyErrorCode,
};
pub use session_checkpoint_json::{
    SESSION_CHECKPOINT_FORMAT, SESSION_CHECKPOINT_FORMAT_VERSION, SessionCheckpointJsonCodec,
};
pub use session_checkpoint_limits::{
    DEFAULT_SESSION_CHECKPOINT_MAX_AGGREGATE_FORWARD_OPERATIONS,
    DEFAULT_SESSION_CHECKPOINT_MAX_HISTORY_CAPACITY, DEFAULT_SESSION_CHECKPOINT_MAX_RETAINED_NODES,
    DEFAULT_SESSION_CHECKPOINT_MAX_RETAINED_PROPERTY_VALUES,
    DEFAULT_SESSION_CHECKPOINT_MAX_RETAINED_TEXT_BYTES, SessionCheckpointLimits,
};
pub use transaction_error::{
    TransactionCodecError, TransactionRecordError, TransactionRecordErrorCode,
    TransactionRecordLocation,
};
pub use transaction_json::{
    TRANSACTION_REQUEST_FORMAT, TRANSACTION_REQUEST_FORMAT_VERSION, TransactionJsonCodec,
};
